# Generated by Django 2.1.2 on 2018-10-05 21:10

from django.db import migrations
import news_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=news_app.models.CloudinaryField(max_length=255),
        ),
    ]
