# Generated by Django 2.1.2 on 2018-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=1, verbose_name='Текст новости'),
            preserve_default=False,
        ),
    ]
