# Generated by Django 2.1.2 on 2018-10-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_post_short_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_content',
        ),
    ]
