# Generated by Django 2.1.2 on 2018-10-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_remove_post_short_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
