# Generated by Django 2.1.2 on 2018-10-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_post_short_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_content',
            field=models.CharField(max_length=255, verbose_name='Краткое описание'),
        ),
    ]
