# Generated by Django 2.1.4 on 2018-12-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Основной Раздел',
                'verbose_name_plural': 'Основные Разделы',
                'db_table': 'categories',
            },
        ),
    ]
