# Generated by Django 2.1.4 on 2018-12-30 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index_app.Category', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
