# Generated by Django 2.1.4 on 2018-12-30 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0003_section_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index_app.Category', verbose_name='Раздел'),
        ),
    ]
