# Generated by Django 2.1.2 on 2018-10-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_feedback_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback_app.FeedbackCategory', verbose_name='Категория вопроса'),
        ),
    ]
